// Generated from the pinned OpenAPI. DO NOT EDIT.
export const operations = [
  {
    id: 'postV1TenantsProvision',
    method: 'POST',
    path: '/v1/tenants/provision',
    principalClasses: ['PLATFORM'],
    permission: 'platform:ops',
  },
  {
    id: 'getV1TenantsId',
    method: 'GET',
    path: '/v1/tenants/{id}',
    principalClasses: ['PLATFORM'],
    permission: 'tenant:read',
  },
  {
    id: 'postV1TenantsIdSuspend',
    method: 'POST',
    path: '/v1/tenants/{id}/suspend',
    principalClasses: ['PLATFORM'],
    permission: 'platform:ops',
  },
  {
    id: 'postV1TenantsIdReactivate',
    method: 'POST',
    path: '/v1/tenants/{id}/reactivate',
    principalClasses: ['PLATFORM'],
    permission: 'platform:ops',
  },
  {
    id: 'putV1TenantsIdSettings',
    method: 'PUT',
    path: '/v1/tenants/{id}/settings',
    principalClasses: ['TENANT', 'PLATFORM'],
    permission: 'tenant:manage',
  },
  {
    id: 'postV1IdentityCredentialsLogin',
    method: 'POST',
    path: '/v1/identity/credentials/login',
    principalClasses: ['ANONYMOUS'],
    permission: null,
  },
  {
    id: 'postV1IdentityTokensRefresh',
    method: 'POST',
    path: '/v1/identity/tokens/refresh',
    principalClasses: ['ANONYMOUS'],
    permission: null,
  },
  {
    id: 'postV1IdentityLogout',
    method: 'POST',
    path: '/v1/identity/logout',
    principalClasses: ['TENANT', 'AGENT', 'PLATFORM'],
    permission: null,
  },
  {
    id: 'postV1IdentityMfaTotpEnrol',
    method: 'POST',
    path: '/v1/identity/mfa/totp/enrol',
    principalClasses: ['TENANT', 'AGENT', 'PLATFORM'],
    permission: null,
  },
  {
    id: 'postV1IdentityMfaTotpVerify',
    method: 'POST',
    path: '/v1/identity/mfa/totp/verify',
    principalClasses: ['TENANT', 'AGENT', 'PLATFORM'],
    permission: null,
  },
  {
    id: 'postV1IdentityApiKeys',
    method: 'POST',
    path: '/v1/identity/api-keys',
    principalClasses: ['AGENT'],
    permission: 'api_key:manage',
  },
  {
    id: 'getV1IdentityApiKeys',
    method: 'GET',
    path: '/v1/identity/api-keys',
    principalClasses: ['AGENT'],
    permission: 'api_key:manage',
  },
  {
    id: 'postV1IdentityApiKeysIdRevoke',
    method: 'POST',
    path: '/v1/identity/api-keys/{id}/revoke',
    principalClasses: ['AGENT'],
    permission: 'api_key:manage',
  },
  {
    id: 'postV1IdentitySsoConfigure',
    method: 'POST',
    path: '/v1/identity/sso/configure',
    principalClasses: ['TENANT'],
    permission: 'user:manage',
  },
  {
    id: 'postV1IdentityRoles',
    method: 'POST',
    path: '/v1/identity/roles',
    principalClasses: ['TENANT'],
    permission: 'user:manage',
  },
  {
    id: 'getV1IdentityRoles',
    method: 'GET',
    path: '/v1/identity/roles',
    principalClasses: ['TENANT'],
    permission: 'user:manage',
  },
  {
    id: 'postV1IdentityRolesAssign',
    method: 'POST',
    path: '/v1/identity/roles/assign',
    principalClasses: ['TENANT'],
    permission: 'user:manage',
  },
  {
    id: 'postV1IdentityPermissionsGrant',
    method: 'POST',
    path: '/v1/identity/permissions/grant',
    principalClasses: ['TENANT'],
    permission: 'user:manage',
  },
  {
    id: 'postV1IdentityPermissionsEvaluate',
    method: 'POST',
    path: '/v1/identity/permissions/evaluate',
    principalClasses: ['TENANT'],
    permission: 'user:manage',
  },
  {
    id: 'postV1IdentityPermissionsInvalidateCache',
    method: 'POST',
    path: '/v1/identity/permissions/invalidate-cache',
    principalClasses: ['TENANT'],
    permission: 'user:manage',
  },
  {
    id: 'postV1IdentityImpersonationStart',
    method: 'POST',
    path: '/v1/identity/impersonation/start',
    principalClasses: ['PLATFORM'],
    permission: 'platform:impersonate',
  },
  {
    id: 'postV1AuditSearch',
    method: 'POST',
    path: '/v1/audit/search',
    principalClasses: ['TENANT'],
    permission: 'audit:read',
  },
  {
    id: 'postV1AuditExport',
    method: 'POST',
    path: '/v1/audit/export',
    principalClasses: ['TENANT'],
    permission: 'audit:read',
  },
  {
    id: 'postV1AuditVerifyChain',
    method: 'POST',
    path: '/v1/audit/verify-chain',
    principalClasses: ['TENANT'],
    permission: 'audit:read',
  },
  {
    id: 'postV1Agents',
    method: 'POST',
    path: '/v1/agents',
    principalClasses: ['TENANT'],
    permission: 'agent:write',
  },
  {
    id: 'postV1AgentsIdUsers',
    method: 'POST',
    path: '/v1/agents/{id}/users',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'agent_user:manage',
  },
  {
    id: 'getV1AgentsIdUsers',
    method: 'GET',
    path: '/v1/agents/{id}/users',
    principalClasses: ['AGENT'],
    permission: 'agent_user:manage',
  },
  {
    id: 'putV1AgentsIdCommercialProfile',
    method: 'PUT',
    path: '/v1/agents/{id}/commercial-profile',
    principalClasses: ['TENANT'],
    permission: 'agent:write',
  },
  {
    id: 'postV1AgentsIdMarkets',
    method: 'POST',
    path: '/v1/agents/{id}/markets',
    principalClasses: ['TENANT'],
    permission: 'market:assign',
  },
  {
    id: 'postV1AgentsIdSuspend',
    method: 'POST',
    path: '/v1/agents/{id}/suspend',
    principalClasses: ['TENANT'],
    permission: 'agent:write',
  },
  {
    id: 'postV1ComplianceSubjects',
    method: 'POST',
    path: '/v1/compliance/subjects',
    principalClasses: ['TENANT'],
    permission: 'tenant:manage',
  },
  {
    id: 'postV1ComplianceSubjectsErase',
    method: 'POST',
    path: '/v1/compliance/subjects/erase',
    principalClasses: ['TENANT'],
    permission: 'tenant:manage',
  },
  {
    id: 'postV1MasterDataEntries',
    method: 'POST',
    path: '/v1/master-data/entries',
    principalClasses: ['PLATFORM', 'TENANT'],
    permission: 'masterdata:write',
  },
  {
    id: 'putV1MasterDataEntriesTenantIdItemIdPublish',
    method: 'PUT',
    path: '/v1/master-data/entries/{tenantId}/{itemId}/publish',
    principalClasses: ['PLATFORM', 'TENANT'],
    permission: 'masterdata:publish',
  },
  {
    id: 'putV1MasterDataEntriesTenantIdItemIdArchive',
    method: 'PUT',
    path: '/v1/master-data/entries/{tenantId}/{itemId}/archive',
    principalClasses: ['PLATFORM', 'TENANT'],
    permission: 'masterdata:archive',
  },
  {
    id: 'postV1MasterDataImportDryRun',
    method: 'POST',
    path: '/v1/master-data/import/dry-run',
    principalClasses: ['PLATFORM', 'TENANT'],
    permission: 'masterdata:write',
  },
  {
    id: 'postV1MasterDataImportConfirm',
    method: 'POST',
    path: '/v1/master-data/import/confirm',
    principalClasses: ['PLATFORM', 'TENANT'],
    permission: 'masterdata:write',
  },
  {
    id: 'postV1MasterDataMarketsResolve',
    method: 'POST',
    path: '/v1/master-data/markets/resolve',
    principalClasses: ['TENANT'],
    permission: 'market:read',
  },
  {
    id: 'postV1BrandingThemesPublish',
    method: 'POST',
    path: '/v1/branding/themes/publish',
    principalClasses: ['TENANT'],
    permission: 'branding:publish',
  },
  {
    id: 'postV1NotificationsSmtpConfigure',
    method: 'POST',
    path: '/v1/notifications/smtp/configure',
    principalClasses: ['TENANT'],
    permission: 'notification:smtp:write',
  },
  {
    id: 'postV1NotificationsSmtpTest',
    method: 'POST',
    path: '/v1/notifications/smtp/test',
    principalClasses: ['TENANT'],
    permission: 'notification:smtp:test',
  },
  {
    id: 'postV1NotificationsRoutesConfigure',
    method: 'POST',
    path: '/v1/notifications/routes/configure',
    principalClasses: ['TENANT'],
    permission: 'notification:routing:write',
  },
  {
    id: 'postV1NotificationsRoutesPreview',
    method: 'POST',
    path: '/v1/notifications/routes/preview',
    principalClasses: ['TENANT'],
    permission: 'notification:routing:read',
  },
  {
    id: 'postV1NotificationsBookingReferencePublishScheme',
    method: 'POST',
    path: '/v1/notifications/booking-reference/publish-scheme',
    principalClasses: ['TENANT'],
    permission: 'booking_number:publish',
  },
  {
    id: 'postV1GeographyAreas',
    method: 'POST',
    path: '/v1/geography/areas',
    principalClasses: ['PLATFORM'],
    permission: 'masterdata:write',
  },
  {
    id: 'postV1GeographyAreasLink',
    method: 'POST',
    path: '/v1/geography/areas/link',
    principalClasses: ['PLATFORM'],
    permission: 'masterdata:map',
  },
  {
    id: 'postV1GeographyGiataIngest',
    method: 'POST',
    path: '/v1/geography/giata/ingest',
    principalClasses: ['PLATFORM'],
    permission: 'masterdata:write',
  },
  {
    id: 'postV1GeographyVersionsPublish',
    method: 'POST',
    path: '/v1/geography/versions/publish',
    principalClasses: ['PLATFORM'],
    permission: 'masterdata:publish',
  },
  {
    id: 'postV1GeographyReconcile',
    method: 'POST',
    path: '/v1/geography/reconcile',
    principalClasses: ['PLATFORM'],
    permission: 'masterdata:map',
  },
  {
    id: 'postV1GeographySuggest',
    method: 'POST',
    path: '/v1/geography/suggest',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'masterdata:read',
  },
  {
    id: 'postV1GeographyHierarchyResolve',
    method: 'POST',
    path: '/v1/geography/hierarchy/resolve',
    principalClasses: ['PLATFORM', 'TENANT', 'AGENT'],
    permission: 'masterdata:read',
  },
  {
    id: 'postV1GeographyAreasSearch',
    method: 'POST',
    path: '/v1/geography/areas/search',
    principalClasses: ['PLATFORM', 'TENANT', 'AGENT'],
    permission: 'masterdata:read',
  },
  {
    id: 'postV1GeographyAliasesManage',
    method: 'POST',
    path: '/v1/geography/aliases/manage',
    principalClasses: ['TENANT'],
    permission: 'masterdata:write',
  },
  {
    id: 'postV1CatalogProducts',
    method: 'POST',
    path: '/v1/catalog/products',
    principalClasses: ['TENANT'],
    permission: 'product:write',
  },
  {
    id: 'getV1CatalogProducts',
    method: 'GET',
    path: '/v1/catalog/products',
    principalClasses: ['TENANT'],
    permission: 'product:read',
  },
  {
    id: 'putV1CatalogProductsId',
    method: 'PUT',
    path: '/v1/catalog/products/{id}',
    principalClasses: ['TENANT'],
    permission: 'product:write',
  },
  {
    id: 'postV1CatalogProductsProductIdOptions',
    method: 'POST',
    path: '/v1/catalog/products/{productId}/options',
    principalClasses: ['TENANT'],
    permission: 'product:write',
  },
  {
    id: 'putV1CatalogProductsProductIdOptionsOptionId',
    method: 'PUT',
    path: '/v1/catalog/products/{productId}/options/{optionId}',
    principalClasses: ['TENANT'],
    permission: 'product:write',
  },
  {
    id: 'postV1CatalogProductsIdActivate',
    method: 'POST',
    path: '/v1/catalog/products/{id}/activate',
    principalClasses: ['TENANT'],
    permission: 'product:activate',
  },
  {
    id: 'postV1CatalogProductsIdValidateReadiness',
    method: 'POST',
    path: '/v1/catalog/products/{id}/validate-readiness',
    principalClasses: ['TENANT'],
    permission: 'product:activate',
  },
  {
    id: 'postV1Contracts',
    method: 'POST',
    path: '/v1/contracts',
    principalClasses: ['TENANT'],
    permission: 'contract:write',
  },
  {
    id: 'getV1Contracts',
    method: 'GET',
    path: '/v1/contracts',
    principalClasses: ['TENANT'],
    permission: 'contract:read',
  },
  {
    id: 'postV1ContractsContractIdVersions',
    method: 'POST',
    path: '/v1/contracts/{contractId}/versions',
    principalClasses: ['TENANT'],
    permission: 'contract:write',
  },
  {
    id: 'postV1ContractsContractIdSeasons',
    method: 'POST',
    path: '/v1/contracts/{contractId}/seasons',
    principalClasses: ['TENANT'],
    permission: 'contract:write',
  },
  {
    id: 'postV1ContractsContractIdRatePlans',
    method: 'POST',
    path: '/v1/contracts/{contractId}/rate-plans',
    principalClasses: ['TENANT'],
    permission: 'contract:write',
  },
  {
    id: 'postV1ContractsContractIdValidatePublication',
    method: 'POST',
    path: '/v1/contracts/{contractId}/validate-publication',
    principalClasses: ['TENANT'],
    permission: 'contract:publish',
  },
  {
    id: 'postV1ContractsContractIdPublish',
    method: 'POST',
    path: '/v1/contracts/{contractId}/publish',
    principalClasses: ['TENANT'],
    permission: 'contract:publish',
  },
  {
    id: 'getV1CatalogContractsImportTemplate',
    method: 'GET',
    path: '/v1/catalog/contracts/import/template',
    principalClasses: ['TENANT'],
    permission: 'contract:import',
  },
  {
    id: 'postV1CatalogContractsImportDryRun',
    method: 'POST',
    path: '/v1/catalog/contracts/import/dry-run',
    principalClasses: ['TENANT'],
    permission: 'contract:import',
  },
  {
    id: 'postV1CatalogContractsImportBatchIdConfirm',
    method: 'POST',
    path: '/v1/catalog/contracts/import/{batchId}/confirm',
    principalClasses: ['TENANT'],
    permission: 'contract:import',
  },
  {
    id: 'postV1CatalogContractsBulkEditDryRun',
    method: 'POST',
    path: '/v1/catalog/contracts/bulk-edit/dry-run',
    principalClasses: ['TENANT'],
    permission: 'contract:write',
  },
  {
    id: 'postV1CatalogContractsBulkEditBatchIdConfirm',
    method: 'POST',
    path: '/v1/catalog/contracts/bulk-edit/{batchId}/confirm',
    principalClasses: ['TENANT'],
    permission: 'contract:write',
  },
  {
    id: 'postV1CatalogProductsProductIdContentPublish',
    method: 'POST',
    path: '/v1/catalog/products/{productId}/content/publish',
    principalClasses: ['TENANT'],
    permission: 'product:write',
  },
  {
    id: 'postV1CatalogProductsProductIdMedia',
    method: 'POST',
    path: '/v1/catalog/products/{productId}/media',
    principalClasses: ['TENANT'],
    permission: 'product:write',
  },
  {
    id: 'postV1RulesSets',
    method: 'POST',
    path: '/v1/rules/sets',
    principalClasses: ['TENANT'],
    permission: 'rule:write',
  },
  {
    id: 'postV1RulesSetsRuleSetIdVersions',
    method: 'POST',
    path: '/v1/rules/sets/{ruleSetId}/versions',
    principalClasses: ['TENANT'],
    permission: 'rule:write',
  },
  {
    id: 'postV1RulesSetsRuleSetIdVersionsVersionPublish',
    method: 'POST',
    path: '/v1/rules/sets/{ruleSetId}/versions/{version}/publish',
    principalClasses: ['TENANT'],
    permission: 'rule:publish',
  },
  {
    id: 'postV1RulesSchemaValidate',
    method: 'POST',
    path: '/v1/rules/schema/validate',
    principalClasses: ['TENANT'],
    permission: 'rule:write',
  },
  {
    id: 'postV1RulesSetsRuleSetIdCompile',
    method: 'POST',
    path: '/v1/rules/sets/{ruleSetId}/compile',
    principalClasses: ['TENANT'],
    permission: 'rule:write',
  },
  {
    id: 'postV1RulesConflictsResolve',
    method: 'POST',
    path: '/v1/rules/conflicts/resolve',
    principalClasses: ['TENANT'],
    permission: 'rule:write',
  },
  {
    id: 'postV1RulesTrace',
    method: 'POST',
    path: '/v1/rules/trace',
    principalClasses: ['TENANT'],
    permission: 'rule:read',
  },
  {
    id: 'postV1RulesCacheInvalidate',
    method: 'POST',
    path: '/v1/rules/cache/invalidate',
    principalClasses: ['TENANT'],
    permission: 'rule:write',
  },
  {
    id: 'postV1RulesPricingEvaluate',
    method: 'POST',
    path: '/v1/rules/pricing/evaluate',
    principalClasses: ['TENANT'],
    permission: 'rule:read',
  },
  {
    id: 'postV1RulesPricingContext',
    method: 'POST',
    path: '/v1/rules/pricing/context',
    principalClasses: ['TENANT'],
    permission: 'rule:write',
  },
  {
    id: 'postV1RulesEvaluationsEvaluationIdExplain',
    method: 'POST',
    path: '/v1/rules/evaluations/{evaluationId}/explain',
    principalClasses: ['TENANT'],
    permission: 'rule:read',
  },
  {
    id: 'postV1PricingBaseRateCalculate',
    method: 'POST',
    path: '/v1/pricing/base-rate/calculate',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1PricingOccupancyApply',
    method: 'POST',
    path: '/v1/pricing/occupancy/apply',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1PricingMealsApply',
    method: 'POST',
    path: '/v1/pricing/meals/apply',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1PricingStayRulesApply',
    method: 'POST',
    path: '/v1/pricing/stay-rules/apply',
    principalClasses: ['TENANT'],
    permission: 'rule:write',
  },
  {
    id: 'postV1PricingPromotionsApply',
    method: 'POST',
    path: '/v1/pricing/promotions/apply',
    principalClasses: ['TENANT'],
    permission: 'promotion:write',
  },
  {
    id: 'postV1PricingCurrencyConvert',
    method: 'POST',
    path: '/v1/pricing/currency/convert',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1PricingTaxCalculate',
    method: 'POST',
    path: '/v1/pricing/tax/calculate',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1PricingMarkupsApply',
    method: 'POST',
    path: '/v1/pricing/markups/apply',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1PricingRound',
    method: 'POST',
    path: '/v1/pricing/round',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1PricingQuoteSign',
    method: 'POST',
    path: '/v1/pricing/quote/sign',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1PricingPreview',
    method: 'POST',
    path: '/v1/pricing/preview',
    principalClasses: ['TENANT'],
    permission: 'pricing:preview',
  },
  {
    id: 'postV1PricingEvaluate',
    method: 'POST',
    path: '/v1/pricing/evaluate',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1PricingContractSimulate',
    method: 'POST',
    path: '/v1/pricing/contract/simulate',
    principalClasses: ['TENANT'],
    permission: 'pricing:preview',
  },
  {
    id: 'postV1InventoryAllotments',
    method: 'POST',
    path: '/v1/inventory/allotments',
    principalClasses: ['TENANT'],
    permission: 'inventory:write',
  },
  {
    id: 'postV1SearchInternal',
    method: 'POST',
    path: '/v1/search/internal',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1SearchFilterEligibility',
    method: 'POST',
    path: '/v1/search/filter-eligibility',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1SearchPrice',
    method: 'POST',
    path: '/v1/search/price',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1SearchOfferToken',
    method: 'POST',
    path: '/v1/search/offer-token',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1SearchResults',
    method: 'POST',
    path: '/v1/search/results',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1SearchFanout',
    method: 'POST',
    path: '/v1/search/fanout',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1SearchMerge',
    method: 'POST',
    path: '/v1/search/merge',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1SearchProgress',
    method: 'POST',
    path: '/v1/search/progress',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1SearchSourcesCancel',
    method: 'POST',
    path: '/v1/search/sources/cancel',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1SearchSpatialGate',
    method: 'POST',
    path: '/v1/search/spatial/gate',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1SearchConcurrencyValidate',
    method: 'POST',
    path: '/v1/search/concurrency/validate',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'postV1BookingsQuotes',
    method: 'POST',
    path: '/v1/bookings/quotes',
    principalClasses: ['AGENT'],
    permission: 'quote:create',
  },
  {
    id: 'getV1BookingsQuotes',
    method: 'GET',
    path: '/v1/bookings/quotes',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'quote:read',
  },
  {
    id: 'postV1BookingsQuotesGet',
    method: 'POST',
    path: '/v1/bookings/quotes/get',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'quote:read',
  },
  {
    id: 'postV1BookingsQuotesRevalidate',
    method: 'POST',
    path: '/v1/bookings/quotes/revalidate',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'quote:read',
  },
  {
    id: 'postV1BookingsQuotesAcceptDrift',
    method: 'POST',
    path: '/v1/bookings/quotes/accept-drift',
    principalClasses: ['AGENT'],
    permission: 'quote:create',
  },
  {
    id: 'postV1Bookings',
    method: 'POST',
    path: '/v1/bookings',
    principalClasses: ['AGENT'],
    permission: 'booking:create',
  },
  {
    id: 'postV1BookingsReferencesAllocate',
    method: 'POST',
    path: '/v1/bookings/references/allocate',
    principalClasses: ['TENANT'],
    permission: 'booking:read',
  },
  {
    id: 'postV1BookingsGet',
    method: 'POST',
    path: '/v1/bookings/get',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'booking:read',
  },
  {
    id: 'postV1BookingsList',
    method: 'POST',
    path: '/v1/bookings/list',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'booking:read',
  },
  {
    id: 'postV1BookingsSagasResume',
    method: 'POST',
    path: '/v1/bookings/sagas/resume',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1BookingsItemsConfirm',
    method: 'POST',
    path: '/v1/bookings/items/confirm',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1BookingsReconcileUnknown',
    method: 'POST',
    path: '/v1/bookings/reconcile/unknown',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1BookingsPassengersAttach',
    method: 'POST',
    path: '/v1/bookings/passengers/attach',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1BookingsCancel',
    method: 'POST',
    path: '/v1/bookings/cancel',
    principalClasses: ['TENANT'],
    permission: 'booking:cancel',
  },
  {
    id: 'postV1BookingsAmend',
    method: 'POST',
    path: '/v1/bookings/amend',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1BookingsCancellationPreview',
    method: 'POST',
    path: '/v1/bookings/cancellation/preview',
    principalClasses: ['TENANT'],
    permission: 'booking:cancel',
  },
  {
    id: 'postV1BookingsAmendmentPreview',
    method: 'POST',
    path: '/v1/bookings/amendment/preview',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1BookingsDeadlines',
    method: 'POST',
    path: '/v1/bookings/deadlines',
    principalClasses: ['TENANT'],
    permission: 'booking:read',
  },
  {
    id: 'postV1DocumentsTemplatesCreate',
    method: 'POST',
    path: '/v1/documents/templates/create',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1DocumentsTemplatesPublish',
    method: 'POST',
    path: '/v1/documents/templates/publish',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1DocumentsRender',
    method: 'POST',
    path: '/v1/documents/render',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1DocumentsRegenerate',
    method: 'POST',
    path: '/v1/documents/regenerate',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1DocumentsDownloadUrl',
    method: 'POST',
    path: '/v1/documents/download-url',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'booking:read',
  },
  {
    id: 'postV1BookingsSagasKill',
    method: 'POST',
    path: '/v1/bookings/sagas/kill',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1BookingsSagasReplay',
    method: 'POST',
    path: '/v1/bookings/sagas/replay',
    principalClasses: ['TENANT'],
    permission: 'booking:read',
  },
  {
    id: 'postV1BookingsConformanceVerify',
    method: 'POST',
    path: '/v1/bookings/conformance/verify',
    principalClasses: ['TENANT'],
    permission: 'booking:read',
  },
  {
    id: 'postV1FinanceAccounts',
    method: 'POST',
    path: '/v1/finance/accounts',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinanceJournals',
    method: 'POST',
    path: '/v1/finance/journals',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinanceJournalsReverse',
    method: 'POST',
    path: '/v1/finance/journals/reverse',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinancePeriodsOpen',
    method: 'POST',
    path: '/v1/finance/periods/open',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinancePeriodsClose',
    method: 'POST',
    path: '/v1/finance/periods/close',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinanceReportsTrialBalance',
    method: 'POST',
    path: '/v1/finance/reports/trial-balance',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'finance:read',
  },
  {
    id: 'postV1FinanceInvoices',
    method: 'POST',
    path: '/v1/finance/invoices',
    principalClasses: ['TENANT'],
    permission: 'invoice:write',
  },
  {
    id: 'postV1FinanceCreditNotes',
    method: 'POST',
    path: '/v1/finance/credit-notes',
    principalClasses: ['TENANT'],
    permission: 'invoice:write',
  },
  {
    id: 'postV1FinancePayments',
    method: 'POST',
    path: '/v1/finance/payments',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinancePaymentsAllocate',
    method: 'POST',
    path: '/v1/finance/payments/allocate',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinanceReportsAging',
    method: 'POST',
    path: '/v1/finance/reports/aging',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'finance:read',
  },
  {
    id: 'postV1FinanceWalletsReserve',
    method: 'POST',
    path: '/v1/finance/wallets/reserve',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinanceWalletsCapture',
    method: 'POST',
    path: '/v1/finance/wallets/capture',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinanceWalletsRelease',
    method: 'POST',
    path: '/v1/finance/wallets/release',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinanceWalletsTopUp',
    method: 'POST',
    path: '/v1/finance/wallets/top-up',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinanceCreditProfiles',
    method: 'POST',
    path: '/v1/finance/credit-profiles',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinanceCreditCheckExposure',
    method: 'POST',
    path: '/v1/finance/credit/check-exposure',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'finance:read',
  },
  {
    id: 'postV1PaymentsIntents',
    method: 'POST',
    path: '/v1/payments/intents',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'payment:create',
  },
  {
    id: 'postV1PaymentsLinks',
    method: 'POST',
    path: '/v1/payments/links',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'payment:create',
  },
  {
    id: 'postV1PaymentsRefundsRequest',
    method: 'POST',
    path: '/v1/payments/refunds/request',
    principalClasses: ['TENANT'],
    permission: 'payment:write',
  },
  {
    id: 'postV1PaymentsRefundsApprove',
    method: 'POST',
    path: '/v1/payments/refunds/approve',
    principalClasses: ['TENANT'],
    permission: 'payment:write',
  },
  {
    id: 'postV1PaymentsSettlementsReconcile',
    method: 'POST',
    path: '/v1/payments/settlements/reconcile',
    principalClasses: ['TENANT'],
    permission: 'payment:write',
  },
  {
    id: 'postV1FinanceJournalsExport',
    method: 'POST',
    path: '/v1/finance/journals/export',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinanceBankStatementsSuggestMatches',
    method: 'POST',
    path: '/v1/finance/bank-statements/suggest-matches',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinanceBankStatementsConfirmMatch',
    method: 'POST',
    path: '/v1/finance/bank-statements/confirm-match',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinanceInvariantsVerify',
    method: 'POST',
    path: '/v1/finance/invariants/verify',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'finance:read',
  },
  {
    id: 'postV1SuppliersPluginsRegister',
    method: 'POST',
    path: '/v1/suppliers/plugins/register',
    principalClasses: ['PLATFORM'],
    permission: 'supplier_plugin:manage',
  },
  {
    id: 'postV1SuppliersPluginsEnable',
    method: 'POST',
    path: '/v1/suppliers/plugins/enable',
    principalClasses: ['PLATFORM'],
    permission: 'supplier_plugin:manage',
  },
  {
    id: 'postV1SuppliersPluginsDisable',
    method: 'POST',
    path: '/v1/suppliers/plugins/disable',
    principalClasses: ['PLATFORM'],
    permission: 'supplier_plugin:manage',
  },
  {
    id: 'postV1SuppliersCredentialsStore',
    method: 'POST',
    path: '/v1/suppliers/credentials/store',
    principalClasses: ['PLATFORM'],
    permission: 'supplier_plugin:manage',
  },
  {
    id: 'postV1SuppliersPluginsTestConnection',
    method: 'POST',
    path: '/v1/suppliers/plugins/test-connection',
    principalClasses: ['PLATFORM'],
    permission: 'supplier_plugin:read',
  },
  {
    id: 'postV1SuppliersPluginsCertify',
    method: 'POST',
    path: '/v1/suppliers/plugins/certify',
    principalClasses: ['PLATFORM'],
    permission: 'supplier_plugin:certify',
  },
  {
    id: 'postV1MappingsProductsCreate',
    method: 'POST',
    path: '/v1/mappings/products/create',
    principalClasses: ['TENANT'],
    permission: 'mapping:write',
  },
  {
    id: 'postV1MappingsProductsApprove',
    method: 'POST',
    path: '/v1/mappings/products/approve',
    principalClasses: ['TENANT'],
    permission: 'mapping:write',
  },
  {
    id: 'postV1MappingsProductsReject',
    method: 'POST',
    path: '/v1/mappings/products/reject',
    principalClasses: ['TENANT'],
    permission: 'mapping:write',
  },
  {
    id: 'postV1MappingsProductsSuggest',
    method: 'POST',
    path: '/v1/mappings/products/suggest',
    principalClasses: ['TENANT'],
    permission: 'mapping:read',
  },
  {
    id: 'postV1MappingsLocationsMap',
    method: 'POST',
    path: '/v1/mappings/locations/map',
    principalClasses: ['TENANT'],
    permission: 'mapping:write',
  },
  {
    id: 'postV1SuppliersGatewayReconcile',
    method: 'POST',
    path: '/v1/suppliers/gateway/reconcile',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1SuppliersPluginsDeadline',
    method: 'POST',
    path: '/v1/suppliers/plugins/deadline',
    principalClasses: ['PLATFORM'],
    permission: 'supplier_plugin:manage',
  },
  {
    id: 'postV1SuppliersPluginsCircuitOpen',
    method: 'POST',
    path: '/v1/suppliers/plugins/circuit/open',
    principalClasses: ['PLATFORM'],
    permission: 'supplier_plugin:manage',
  },
  {
    id: 'postV1SuppliersOperationsReconcileUnknown',
    method: 'POST',
    path: '/v1/suppliers/operations/reconcile-unknown',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1SuppliersPluginsRollback',
    method: 'POST',
    path: '/v1/suppliers/plugins/rollback',
    principalClasses: ['PLATFORM'],
    permission: 'supplier_plugin:manage',
  },
  {
    id: 'postV1SuppliersPluginsKill',
    method: 'POST',
    path: '/v1/suppliers/plugins/kill',
    principalClasses: ['PLATFORM'],
    permission: 'supplier_plugin:manage',
  },
  {
    id: 'postV1NotificationsTemplates',
    method: 'POST',
    path: '/v1/notifications/templates',
    principalClasses: ['TENANT'],
    permission: 'notification:template:write',
  },
  {
    id: 'postV1NotificationsTemplatesTemplateIdPublish',
    method: 'POST',
    path: '/v1/notifications/templates/{templateId}/publish',
    principalClasses: ['TENANT'],
    permission: 'notification:template:publish',
  },
  {
    id: 'postV1NotificationsPreferences',
    method: 'POST',
    path: '/v1/notifications/preferences',
    principalClasses: ['TENANT'],
    permission: 'notification:write',
  },
  {
    id: 'postV1Packages',
    method: 'POST',
    path: '/v1/packages',
    principalClasses: ['TENANT'],
    permission: 'product:write',
  },
  {
    id: 'postV1PackagesPackageIdPublish',
    method: 'POST',
    path: '/v1/packages/{packageId}/publish',
    principalClasses: ['TENANT'],
    permission: 'product:write',
  },
  {
    id: 'postV1PackagesPackageIdComponents',
    method: 'POST',
    path: '/v1/packages/{packageId}/components',
    principalClasses: ['TENANT'],
    permission: 'product:write',
  },
  {
    id: 'postV1PackagesTrips',
    method: 'POST',
    path: '/v1/packages/trips',
    principalClasses: ['TENANT'],
    permission: 'product:write',
  },
  {
    id: 'postV1PackagesTripsTripIdItinerary',
    method: 'POST',
    path: '/v1/packages/trips/{tripId}/itinerary',
    principalClasses: ['TENANT'],
    permission: 'product:write',
  },
  {
    id: 'postV1PackagesDepartures',
    method: 'POST',
    path: '/v1/packages/departures',
    principalClasses: ['TENANT'],
    permission: 'product:write',
  },
  {
    id: 'postV1OperationsCases',
    method: 'POST',
    path: '/v1/operations/cases',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'getV1OperationsCases',
    method: 'GET',
    path: '/v1/operations/cases',
    principalClasses: ['TENANT'],
    permission: 'operation:read',
  },
  {
    id: 'postV1OperationsCasesCaseIdAssign',
    method: 'POST',
    path: '/v1/operations/cases/{caseId}/assign',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1OperationsCasesCaseIdEscalate',
    method: 'POST',
    path: '/v1/operations/cases/{caseId}/escalate',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1OperationsNotes',
    method: 'POST',
    path: '/v1/operations/notes',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1OperationsAttachments',
    method: 'POST',
    path: '/v1/operations/attachments',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1OperationsCommunicationsThreads',
    method: 'POST',
    path: '/v1/operations/communications/threads',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1OperationsRelocations',
    method: 'POST',
    path: '/v1/operations/relocations',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1ReportingDefinitions',
    method: 'POST',
    path: '/v1/reporting/definitions',
    principalClasses: ['TENANT'],
    permission: 'report:read',
  },
  {
    id: 'postV1ReportingRuns',
    method: 'POST',
    path: '/v1/reporting/runs',
    principalClasses: ['TENANT'],
    permission: 'report:read',
  },
  {
    id: 'postV1ReportingExports',
    method: 'POST',
    path: '/v1/reporting/exports',
    principalClasses: ['TENANT'],
    permission: 'report:read',
  },
  {
    id: 'postV1ReportingSchedules',
    method: 'POST',
    path: '/v1/reporting/schedules',
    principalClasses: ['TENANT'],
    permission: 'report:read',
  },
  {
    id: 'getV1PublicStorefront',
    method: 'GET',
    path: '/v1/public/storefront',
    principalClasses: ['ANONYMOUS'],
    permission: null,
  },
  {
    id: 'getV1PublicContentHome',
    method: 'GET',
    path: '/v1/public/content/home',
    principalClasses: ['ANONYMOUS'],
    permission: null,
  },
  {
    id: 'getV1PublicDestinationSuggestions',
    method: 'GET',
    path: '/v1/public/destinations/suggestions',
    principalClasses: ['ANONYMOUS'],
    permission: null,
  },
  {
    id: 'postV1PublicSearches',
    method: 'POST',
    path: '/v1/public/searches',
    principalClasses: ['ANONYMOUS_OR_GUEST'],
    permission: null,
  },
  {
    id: 'getV1PublicSearchesSearchId',
    method: 'GET',
    path: '/v1/public/searches/{searchId}',
    principalClasses: ['ANONYMOUS_OR_GUEST'],
    permission: null,
  },
  {
    id: 'getV1PublicSearchesSearchIdOffersOfferId',
    method: 'GET',
    path: '/v1/public/searches/{searchId}/offers/{offerId}',
    principalClasses: ['ANONYMOUS_OR_GUEST'],
    permission: null,
  },
  {
    id: 'getV1PublicProductsProductSlug',
    method: 'GET',
    path: '/v1/public/products/{productSlug}',
    principalClasses: ['ANONYMOUS'],
    permission: null,
  },
  {
    id: 'postV1PublicGuestSessions',
    method: 'POST',
    path: '/v1/public/guest-sessions',
    principalClasses: ['ANONYMOUS'],
    permission: null,
  },
  {
    id: 'postV1PublicCustomers',
    method: 'POST',
    path: '/v1/public/customers',
    principalClasses: ['GUEST'],
    permission: null,
  },
  {
    id: 'postV1PublicGuestSessionsSessionIdEmailChallenges',
    method: 'POST',
    path: '/v1/public/guest-sessions/{sessionId}/email-challenges',
    principalClasses: ['GUEST'],
    permission: null,
  },
  {
    id: 'postV1PublicGuestSessionsSessionIdEmailVerification',
    method: 'POST',
    path: '/v1/public/guest-sessions/{sessionId}/email-verification',
    principalClasses: ['GUEST'],
    permission: null,
  },
  {
    id: 'postV1PublicQuotes',
    method: 'POST',
    path: '/v1/public/quotes',
    principalClasses: ['GUEST'],
    permission: null,
  },
  {
    id: 'getV1PublicQuotesQuoteId',
    method: 'GET',
    path: '/v1/public/quotes/{quoteId}',
    principalClasses: ['GUEST'],
    permission: null,
  },
  {
    id: 'postV1PublicCheckouts',
    method: 'POST',
    path: '/v1/public/checkouts',
    principalClasses: ['VERIFIED_GUEST_OR_CUSTOMER'],
    permission: null,
  },
  {
    id: 'getV1PublicCheckoutsCheckoutId',
    method: 'GET',
    path: '/v1/public/checkouts/{checkoutId}',
    principalClasses: ['VERIFIED_GUEST_OR_CUSTOMER'],
    permission: null,
  },
  {
    id: 'getV1PublicPaymentsReturn',
    method: 'GET',
    path: '/v1/public/payments/return',
    principalClasses: ['HOSTED_PAYMENT_RETURN'],
    permission: null,
  },
  {
    id: 'postV1PublicConsents',
    method: 'POST',
    path: '/v1/public/consents',
    principalClasses: ['GUEST_OR_CUSTOMER'],
    permission: null,
  },
  {
    id: 'postV1PublicBookingsAccessChallenges',
    method: 'POST',
    path: '/v1/public/bookings/access-challenges',
    principalClasses: ['ANONYMOUS'],
    permission: null,
  },
  {
    id: 'postV1PublicBookingsAccessChallengesChallengeIdVerify',
    method: 'POST',
    path: '/v1/public/bookings/access-challenges/{challengeId}/verify',
    principalClasses: ['ANONYMOUS'],
    permission: null,
  },
  {
    id: 'getV1PublicBookingsBookingReference',
    method: 'GET',
    path: '/v1/public/bookings/{bookingReference}',
    principalClasses: ['BOOKING_ACCESS_SESSION'],
    permission: null,
  },
  {
    id: 'getV1PublicBookingsBookingReferenceDocuments',
    method: 'GET',
    path: '/v1/public/bookings/{bookingReference}/documents',
    principalClasses: ['BOOKING_ACCESS_SESSION'],
    permission: null,
  },
  {
    id: 'getV1PublicBookingsBookingReferenceCancellationQuote',
    method: 'GET',
    path: '/v1/public/bookings/{bookingReference}/cancellation-quote',
    principalClasses: ['BOOKING_ACCESS_SESSION'],
    permission: null,
  },
  {
    id: 'postV1PublicBookingsBookingReferenceCancellations',
    method: 'POST',
    path: '/v1/public/bookings/{bookingReference}/cancellations',
    principalClasses: ['BOOKING_ACCESS_SESSION'],
    permission: null,
  },
  {
    id: 'postV1SearchSavedSearches',
    method: 'POST',
    path: '/v1/search/saved-searches',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'search:saved:write',
  },
  {
    id: 'getV1SearchSavedSearches',
    method: 'GET',
    path: '/v1/search/saved-searches',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'search:saved:read',
  },
  {
    id: 'getV1SearchSavedSearchesSavedSearchId',
    method: 'GET',
    path: '/v1/search/saved-searches/{savedSearchId}',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'search:saved:read',
  },
  {
    id: 'putV1SearchSavedSearchesSavedSearchId',
    method: 'PUT',
    path: '/v1/search/saved-searches/{savedSearchId}',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'search:saved:write',
  },
  {
    id: 'deleteV1SearchSavedSearchesSavedSearchId',
    method: 'DELETE',
    path: '/v1/search/saved-searches/{savedSearchId}',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'search:saved:write',
  },
  {
    id: 'postV1SearchSavedSearchesSavedSearchIdExecute',
    method: 'POST',
    path: '/v1/search/saved-searches/{savedSearchId}/execute',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'search:saved:read',
  },
  {
    id: 'postV1PlatformPlans',
    method: 'POST',
    path: '/v1/platform/plans',
    principalClasses: ['PLATFORM'],
    permission: 'plan:manage',
  },
  {
    id: 'getV1PlatformPlans',
    method: 'GET',
    path: '/v1/platform/plans',
    principalClasses: ['PLATFORM'],
    permission: 'plan:manage',
  },
  {
    id: 'getV1PlatformPlansPlanId',
    method: 'GET',
    path: '/v1/platform/plans/{planId}',
    principalClasses: ['PLATFORM'],
    permission: 'plan:manage',
  },
  {
    id: 'putV1PlatformPlansPlanId',
    method: 'PUT',
    path: '/v1/platform/plans/{planId}',
    principalClasses: ['PLATFORM'],
    permission: 'plan:manage',
  },
  {
    id: 'postV1PlatformPlansPlanIdVersions',
    method: 'POST',
    path: '/v1/platform/plans/{planId}/versions',
    principalClasses: ['PLATFORM'],
    permission: 'plan:manage',
  },
  {
    id: 'getV1PlatformPlansPlanIdVersions',
    method: 'GET',
    path: '/v1/platform/plans/{planId}/versions',
    principalClasses: ['PLATFORM'],
    permission: 'plan:manage',
  },
  {
    id: 'postV1PlatformPlansPlanIdVersionsVersionIdPublish',
    method: 'POST',
    path: '/v1/platform/plans/{planId}/versions/{versionId}/publish',
    principalClasses: ['PLATFORM'],
    permission: 'plan:manage',
  },
  {
    id: 'postV1PlatformPlansPlanIdRetire',
    method: 'POST',
    path: '/v1/platform/plans/{planId}/retire',
    principalClasses: ['PLATFORM'],
    permission: 'plan:manage',
  },
  {
    id: 'getV1PlatformTenantsTenantIdSubscription',
    method: 'GET',
    path: '/v1/platform/tenants/{tenantId}/subscription',
    principalClasses: ['PLATFORM'],
    permission: 'plan:manage',
  },
  {
    id: 'putV1PlatformTenantsTenantIdSubscription',
    method: 'PUT',
    path: '/v1/platform/tenants/{tenantId}/subscription',
    principalClasses: ['PLATFORM'],
    permission: 'plan:manage',
  },
  {
    id: 'getV1PlatformOperationsHealth',
    method: 'GET',
    path: '/v1/platform/operations/health',
    principalClasses: ['PLATFORM'],
    permission: 'platform:ops',
  },
  {
    id: 'getV1SearchSearchIdOffersOfferId',
    method: 'GET',
    path: '/v1/search/{searchId}/offers/{offerId}',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'pricing:evaluate',
  },
  {
    id: 'getV1FinanceAgentSummary',
    method: 'GET',
    path: '/v1/finance/agent-summary',
    principalClasses: ['AGENT'],
    permission: 'finance:read',
  },
  {
    id: 'getV1NotificationsInbox',
    method: 'GET',
    path: '/v1/notifications/inbox',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'notification:read',
  },
  {
    id: 'getV1NotificationsInboxUnreadCount',
    method: 'GET',
    path: '/v1/notifications/inbox/unread-count',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'notification:read',
  },
  {
    id: 'getV1NotificationsInboxNotificationId',
    method: 'GET',
    path: '/v1/notifications/inbox/{notificationId}',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'notification:read',
  },
  {
    id: 'postV1NotificationsInboxNotificationIdRead',
    method: 'POST',
    path: '/v1/notifications/inbox/{notificationId}/read',
    principalClasses: ['TENANT', 'AGENT'],
    permission: 'notification:write',
  },
  {
    id: 'getV1AgentsIdUsersUserId',
    method: 'GET',
    path: '/v1/agents/{id}/users/{userId}',
    principalClasses: ['AGENT'],
    permission: 'agent_user:manage',
  },
  {
    id: 'putV1AgentsIdUsersUserId',
    method: 'PUT',
    path: '/v1/agents/{id}/users/{userId}',
    principalClasses: ['AGENT'],
    permission: 'agent_user:manage',
  },
  {
    id: 'postV1AgentsIdUsersUserIdActivate',
    method: 'POST',
    path: '/v1/agents/{id}/users/{userId}/activate',
    principalClasses: ['AGENT'],
    permission: 'agent_user:manage',
  },
  {
    id: 'postV1AgentsIdUsersUserIdDeactivate',
    method: 'POST',
    path: '/v1/agents/{id}/users/{userId}/deactivate',
    principalClasses: ['AGENT'],
    permission: 'agent_user:manage',
  },
  {
    id: 'postV1IdentityApiKeysIdRotate',
    method: 'POST',
    path: '/v1/identity/api-keys/{id}/rotate',
    principalClasses: ['AGENT'],
    permission: 'api_key:manage',
  },
  {
    id: 'getV1IdentityUsers',
    method: 'GET',
    path: '/v1/identity/users',
    principalClasses: ['TENANT'],
    permission: 'user:manage',
  },
  {
    id: 'postV1IdentityUsers',
    method: 'POST',
    path: '/v1/identity/users',
    principalClasses: ['TENANT'],
    permission: 'user:manage',
  },
  {
    id: 'postV1IdentityUsersIdActivate',
    method: 'POST',
    path: '/v1/identity/users/{id}/activate',
    principalClasses: ['TENANT'],
    permission: 'user:manage',
  },
  {
    id: 'postV1IdentityUsersIdDeactivate',
    method: 'POST',
    path: '/v1/identity/users/{id}/deactivate',
    principalClasses: ['TENANT'],
    permission: 'user:manage',
  },
  {
    id: 'getV1IdentityPermissions',
    method: 'GET',
    path: '/v1/identity/permissions',
    principalClasses: ['TENANT'],
    permission: 'user:manage',
  },
  {
    id: 'postV1IdentityRolesUnassign',
    method: 'POST',
    path: '/v1/identity/roles/unassign',
    principalClasses: ['TENANT'],
    permission: 'user:manage',
  },
  {
    id: 'postV1IdentityPermissionsRevoke',
    method: 'POST',
    path: '/v1/identity/permissions/revoke',
    principalClasses: ['TENANT'],
    permission: 'user:manage',
  },
  {
    id: 'postV1BrandingThemes',
    method: 'POST',
    path: '/v1/branding/themes',
    principalClasses: ['TENANT'],
    permission: 'branding:write',
  },
  {
    id: 'getV1BrandingThemesCurrent',
    method: 'GET',
    path: '/v1/branding/themes/current',
    principalClasses: ['TENANT'],
    permission: 'branding:read',
  },
  {
    id: 'putV1BrandingThemesThemeIdDraft',
    method: 'PUT',
    path: '/v1/branding/themes/{themeId}/draft',
    principalClasses: ['TENANT'],
    permission: 'branding:write',
  },
  {
    id: 'postV1BrandingThemesThemeIdValidate',
    method: 'POST',
    path: '/v1/branding/themes/{themeId}/validate',
    principalClasses: ['TENANT'],
    permission: 'branding:write',
  },
  {
    id: 'postV1BrandingThemesThemeIdPreview',
    method: 'POST',
    path: '/v1/branding/themes/{themeId}/preview',
    principalClasses: ['TENANT'],
    permission: 'branding:read',
  },
  {
    id: 'getV1BrandingThemesThemeIdVersions',
    method: 'GET',
    path: '/v1/branding/themes/{themeId}/versions',
    principalClasses: ['TENANT'],
    permission: 'branding:read',
  },
  {
    id: 'postV1BrandingThemesThemeIdRollback',
    method: 'POST',
    path: '/v1/branding/themes/{themeId}/rollback',
    principalClasses: ['TENANT'],
    permission: 'branding:rollback',
  },
  {
    id: 'getV1OperationsCasesCaseId',
    method: 'GET',
    path: '/v1/operations/cases/{caseId}',
    principalClasses: ['TENANT'],
    permission: 'operation:read',
  },
  {
    id: 'getV1Tenants',
    method: 'GET',
    path: '/v1/tenants',
    principalClasses: ['PLATFORM'],
    permission: 'tenant:read',
  },
  {
    id: 'getV1TenantsIdSummary',
    method: 'GET',
    path: '/v1/tenants/{id}/summary',
    principalClasses: ['PLATFORM'],
    permission: 'tenant:read',
  },
  {
    id: 'postV1AgentsUpdate',
    method: 'POST',
    path: '/v1/agents/update',
    principalClasses: ['TENANT'],
    permission: 'agent:write',
  },
  {
    id: 'postV1CatalogProductsIdDeactivate',
    method: 'POST',
    path: '/v1/catalog/products/{id}/deactivate',
    principalClasses: ['TENANT'],
    permission: 'product:activate',
  },
  {
    id: 'postV1CatalogProductsIdReactivate',
    method: 'POST',
    path: '/v1/catalog/products/{id}/reactivate',
    principalClasses: ['TENANT'],
    permission: 'product:activate',
  },
  {
    id: 'postV1CatalogProductsIdArchive',
    method: 'POST',
    path: '/v1/catalog/products/{id}/archive',
    principalClasses: ['TENANT'],
    permission: 'product:archive',
  },
  {
    id: 'postV1ContractsContractIdMarkets',
    method: 'POST',
    path: '/v1/contracts/{contractId}/markets',
    principalClasses: ['TENANT'],
    permission: 'contract:write',
  },
  {
    id: 'postV1ContractsContractIdPolicies',
    method: 'POST',
    path: '/v1/contracts/{contractId}/policies',
    principalClasses: ['TENANT'],
    permission: 'contract:write',
  },
  {
    id: 'postV1ContractsContractIdOperatingDays',
    method: 'POST',
    path: '/v1/contracts/{contractId}/operating-days',
    principalClasses: ['TENANT'],
    permission: 'contract:write',
  },
  {
    id: 'postV1ContractsContractIdDeactivate',
    method: 'POST',
    path: '/v1/contracts/{contractId}/deactivate',
    principalClasses: ['TENANT'],
    permission: 'contract:archive',
  },
  {
    id: 'getV1ContractVersionsContractVersionIdRateGrid',
    method: 'GET',
    path: '/v1/contract-versions/{contractVersionId}/rate-grid',
    principalClasses: ['TENANT'],
    permission: 'contract:read',
  },
  {
    id: 'putV1RatePlansRatePlanIdPricingConfig',
    method: 'PUT',
    path: '/v1/rate-plans/{ratePlanId}/pricing-config',
    principalClasses: ['TENANT'],
    permission: 'contract:write',
  },
  {
    id: 'postV1ContractVersionsContractVersionIdRateGridDryRun',
    method: 'POST',
    path: '/v1/contract-versions/{contractVersionId}/rate-grid/dry-run',
    principalClasses: ['TENANT'],
    permission: 'contract:write',
  },
  {
    id: 'postV1ContractVersionsContractVersionIdRateGridConfirm',
    method: 'POST',
    path: '/v1/contract-versions/{contractVersionId}/rate-grid/confirm',
    principalClasses: ['TENANT'],
    permission: 'contract:write',
  },
  {
    id: 'getV1RatePlansRatePlanIdOccupancyPricing',
    method: 'GET',
    path: '/v1/rate-plans/{ratePlanId}/occupancy-pricing',
    principalClasses: ['TENANT'],
    permission: 'contract:read',
  },
  {
    id: 'putV1RatePlansRatePlanIdOccupancyPricing',
    method: 'PUT',
    path: '/v1/rate-plans/{ratePlanId}/occupancy-pricing',
    principalClasses: ['TENANT'],
    permission: 'contract:write',
  },
  {
    id: 'postV1DispatchVehicles',
    method: 'POST',
    path: '/v1/dispatch/vehicles',
    principalClasses: ['TENANT'],
    permission: 'dispatch:manage',
  },
  {
    id: 'postV1DispatchStaff',
    method: 'POST',
    path: '/v1/dispatch/staff',
    principalClasses: ['TENANT'],
    permission: 'dispatch:manage',
  },
  {
    id: 'postV1DispatchAvailability',
    method: 'POST',
    path: '/v1/dispatch/availability',
    principalClasses: ['TENANT'],
    permission: 'dispatch:manage',
  },
  {
    id: 'postV1DispatchAssignments',
    method: 'POST',
    path: '/v1/dispatch/assignments',
    principalClasses: ['TENANT'],
    permission: 'dispatch:manage',
  },
  {
    id: 'postV1DispatchConflictsCheck',
    method: 'POST',
    path: '/v1/dispatch/conflicts/check',
    principalClasses: ['TENANT'],
    permission: 'dispatch:manage',
  },
  {
    id: 'postV1DispatchReportsMovement',
    method: 'POST',
    path: '/v1/dispatch/reports/movement',
    principalClasses: ['TENANT'],
    permission: 'dispatch:manage',
  },
  {
    id: 'postV1DispatchManifestsGenerate',
    method: 'POST',
    path: '/v1/dispatch/manifests/generate',
    principalClasses: ['TENANT'],
    permission: 'dispatch:manage',
  },
  {
    id: 'postV1DispatchSchedulesGenerate',
    method: 'POST',
    path: '/v1/dispatch/schedules/generate',
    principalClasses: ['TENANT'],
    permission: 'dispatch:manage',
  },
  {
    id: 'getV1DispatchUnassigned',
    method: 'GET',
    path: '/v1/dispatch/unassigned',
    principalClasses: ['TENANT'],
    permission: 'dispatch:manage',
  },
  {
    id: 'postV1DispatchFulfillmentStatus',
    method: 'POST',
    path: '/v1/dispatch/fulfillment/status',
    principalClasses: ['TENANT'],
    permission: 'dispatch:manage',
  },
  {
    id: 'postV1DispatchDisruptionsRaise',
    method: 'POST',
    path: '/v1/dispatch/disruptions/raise',
    principalClasses: ['TENANT'],
    permission: 'dispatch:manage',
  },
  {
    id: 'postV1FinanceEinvoicesSubmit',
    method: 'POST',
    path: '/v1/finance/einvoices/submit',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinanceEinvoicesCorrect',
    method: 'POST',
    path: '/v1/finance/einvoices/correct',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinanceErpJournalsExport',
    method: 'POST',
    path: '/v1/finance/erp/journals/export',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinanceBankStatementsImport',
    method: 'POST',
    path: '/v1/finance/bank-statements/import',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1FinanceBankLinesReconcile',
    method: 'POST',
    path: '/v1/finance/bank-lines/reconcile',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1GroupsQuotes',
    method: 'POST',
    path: '/v1/groups/quotes',
    principalClasses: ['AGENT'],
    permission: 'quote:create',
  },
  {
    id: 'postV1GroupsReservations',
    method: 'POST',
    path: '/v1/groups/reservations',
    principalClasses: ['AGENT'],
    permission: 'booking:create',
  },
  {
    id: 'postV1GroupsDeadlines',
    method: 'POST',
    path: '/v1/groups/deadlines',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1GroupsWashDown',
    method: 'POST',
    path: '/v1/groups/wash-down',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1GroupsRoomingList',
    method: 'POST',
    path: '/v1/groups/rooming-list',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1GroupsPaymentSchedules',
    method: 'POST',
    path: '/v1/groups/payment-schedules',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1GroupsInstallments',
    method: 'POST',
    path: '/v1/groups/installments',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1GroupsInstallmentReminders',
    method: 'POST',
    path: '/v1/groups/installment-reminders',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1GroupsOverdueBalances',
    method: 'POST',
    path: '/v1/groups/overdue-balances',
    principalClasses: ['TENANT'],
    permission: 'finance:write',
  },
  {
    id: 'postV1GroupsExpiredOptions',
    method: 'POST',
    path: '/v1/groups/expired-options',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1IdentityImpersonationRevoke',
    method: 'POST',
    path: '/v1/identity/impersonation/revoke',
    principalClasses: ['PLATFORM'],
    permission: 'platform:impersonate',
  },
  {
    id: 'postV1MigrationBatches',
    method: 'POST',
    path: '/v1/migration/batches',
    principalClasses: ['TENANT'],
    permission: 'migration:manage',
  },
  {
    id: 'postV1MigrationBatchesDryRun',
    method: 'POST',
    path: '/v1/migration/batches/dry-run',
    principalClasses: ['TENANT'],
    permission: 'migration:manage',
  },
  {
    id: 'postV1MigrationBatchesConfirm',
    method: 'POST',
    path: '/v1/migration/batches/confirm',
    principalClasses: ['TENANT'],
    permission: 'migration:manage',
  },
  {
    id: 'postV1MigrationBatchesResume',
    method: 'POST',
    path: '/v1/migration/batches/resume',
    principalClasses: ['TENANT'],
    permission: 'migration:manage',
  },
  {
    id: 'postV1MigrationBatchesRollback',
    method: 'POST',
    path: '/v1/migration/batches/rollback',
    principalClasses: ['TENANT'],
    permission: 'migration:manage',
  },
  {
    id: 'postV1MigrationTemplatesGenerate',
    method: 'POST',
    path: '/v1/migration/templates/generate',
    principalClasses: ['TENANT'],
    permission: 'migration:manage',
  },
  {
    id: 'postV1MigrationEntitiesImport',
    method: 'POST',
    path: '/v1/migration/entities/import',
    principalClasses: ['TENANT'],
    permission: 'migration:manage',
  },
  {
    id: 'postV1MigrationBookingsHistorical',
    method: 'POST',
    path: '/v1/migration/bookings/historical',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1MigrationBookingsInflightActivate',
    method: 'POST',
    path: '/v1/migration/bookings/inflight/activate',
    principalClasses: ['TENANT'],
    permission: 'booking:amend',
  },
  {
    id: 'postV1MigrationBalancesOpening',
    method: 'POST',
    path: '/v1/migration/balances/opening',
    principalClasses: ['TENANT'],
    permission: 'migration:manage',
  },
  {
    id: 'postV1MigrationCutoverReconcile',
    method: 'POST',
    path: '/v1/migration/cutover/reconcile',
    principalClasses: ['TENANT'],
    permission: 'migration:manage',
  },
  {
    id: 'postV1PricingPoliciesValidate',
    method: 'POST',
    path: '/v1/pricing/policies/validate',
    principalClasses: ['TENANT'],
    permission: 'pricing:write',
  },
  {
    id: 'postV1PricingPoliciesPricingPolicyIdPublish',
    method: 'POST',
    path: '/v1/pricing/policies/{pricingPolicyId}/publish',
    principalClasses: ['TENANT'],
    permission: 'pricing:publish',
  },
  {
    id: 'postV1PromotionsPools',
    method: 'POST',
    path: '/v1/promotions/pools',
    principalClasses: ['TENANT'],
    permission: 'promotion:write',
  },
  {
    id: 'postV1PromotionsCodesBatch',
    method: 'POST',
    path: '/v1/promotions/codes/batch',
    principalClasses: ['TENANT'],
    permission: 'promotion:write',
  },
  {
    id: 'postV1PromotionsRedemptionsReserve',
    method: 'POST',
    path: '/v1/promotions/redemptions/reserve',
    principalClasses: ['TENANT'],
    permission: 'promotion:write',
  },
  {
    id: 'postV1PromotionsRedemptionsRelease',
    method: 'POST',
    path: '/v1/promotions/redemptions/release',
    principalClasses: ['TENANT'],
    permission: 'promotion:write',
  },
  {
    id: 'postV1PromotionsReportsPerformance',
    method: 'POST',
    path: '/v1/promotions/reports/performance',
    principalClasses: ['TENANT'],
    permission: 'promotion:read',
  },
  {
    id: 'postV1PromotionsValidate',
    method: 'POST',
    path: '/v1/promotions/validate',
    principalClasses: ['TENANT'],
    permission: 'promotion:write',
  },
  {
    id: 'postV1PromotionsPromotionIdPublish',
    method: 'POST',
    path: '/v1/promotions/{promotionId}/publish',
    principalClasses: ['TENANT'],
    permission: 'promotion:publish',
  },
  {
    id: 'postV1RuleSetsValidate',
    method: 'POST',
    path: '/v1/rule-sets/validate',
    principalClasses: ['TENANT'],
    permission: 'rule:write',
  },
] as const;
export type OperationId = (typeof operations)[number]['id'];
